Organizations:

    - &OrdererOrg
        Name: OrdererOrg
        ID: OrdererMSP
        MSPDir: ../../setup1/vm4/crypto-config/ordererOrganizations/example.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('OrdererMSP.admin')"

    - &Org1
        Name: ${ORG1_NAME}MSP
        ID: ${ORG1_NAME}MSP

        MSPDir: ${ORG1_MSP_DIR}

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('${ORG1_NAME}MSP.admin', '${ORG1_NAME}MSP.peer', '${ORG1_NAME}MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('${ORG1_NAME}MSP.admin', '${ORG1_NAME}MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('${ORG1_NAME}MSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('${ORG1_NAME}MSP.peer')"

        AnchorPeers:
            - Host: ${PEER0_ORG1_HOST}
              Port: 7051

    - &Org2
        Name: ${ORG2_NAME}MSP

        ID: ${ORG2_NAME}MSP

        MSPDir: ${ORG2_MSP_DIR}

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('${ORG2_NAME}MSP.admin', '${ORG2_NAME}MSP.peer', '${ORG2_NAME}MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('${ORG2_NAME}MSP.admin', '${ORG2_NAME}MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('${ORG2_NAME}MSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('${ORG2_NAME}MSP.peer')"

        AnchorPeers:
            - Host: ${PEER0_ORG2_HOST}
              Port: 9051

    - &Org3
        Name: ${ORG3_NAME}MSP

        ID: ${ORG3_NAME}MSP

        MSPDir: ${ORG3_MSP_DIR}

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('${ORG3_NAME}MSP.admin', '${ORG3_NAME}MSP.peer', '${ORG3_NAME}MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('${ORG3_NAME}MSP.admin', '${ORG3_NAME}MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('${ORG3_NAME}MSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('${ORG3_NAME}MSP.peer')"

        AnchorPeers:
            - Host: ${PEER0_ORG3_HOST}
              Port: 11051

Capabilities:
    Channel: &ChannelCapabilities
        V2_0: true

    Orderer: &OrdererCapabilities
        V2_0: true

    Application: &ApplicationCapabilities
        V2_0: true

Application: &ApplicationDefaults

    Organizations:

    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        LifecycleEndorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
        Endorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"

    Capabilities:
        <<: *ApplicationCapabilities

Orderer: &OrdererDefaults

    OrdererType: etcdraft

    EtcdRaft:
        Consenters:
        - Host: ${ORDERER_HOST}
          Port: 7050
          ClientTLSCert: ${ORDERER_TLS_CERT_PATH}
          ServerTLSCert: ${ORDERER_TLS_CERT_PATH}
    Addresses:
        - ${ORDERER_HOST}:7050

    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB

    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"

Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

    Capabilities:
        <<: *ChannelCapabilities

Profiles:

    BasicChannel:
        Consortium: SampleConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Org1
                - *Org2
                - *Org3
            Capabilities:
                <<: *ApplicationCapabilities

    OrdererGenesis:
        <<: *ChannelDefaults
        Capabilities:
            <<: *ChannelCapabilities
        Orderer:
            <<: *OrdererDefaults
            OrdererType: etcdraft
            EtcdRaft:
                Consenters:
                - Host: ${ORDERER_HOST}
                  Port: 7050
                  ClientTLSCert: ${ORDERER_TLS_CERT_PATH}
                  ServerTLSCert: ${ORDERER_TLS_CERT_PATH}
                - Host: ${ORDERER2_HOST}
                  Port: 8050
                  ClientTLSCert: ../../setup1/vm4/crypto-config/ordererOrganizations/example.com/orderers/${ORDERER2_HOST}/tls/server.crt
                  ServerTLSCert: ../../setup1/vm4/crypto-config/ordererOrganizations/example.com/orderers/${ORDERER2_HOST}/tls/server.crt
                - Host: ${ORDERER3_HOST}
                  Port: 9050
                  ClientTLSCert: ../../setup1/vm4/crypto-config/ordererOrganizations/example.com/orderers/${ORDERER3_HOST}/tls/server.crt
                  ServerTLSCert: ../../setup1/vm4/crypto-config/ordererOrganizations/example.com/orderers/${ORDERER3_HOST}/tls/server.crt
            Addresses:
                - ${ORDERER_HOST}:7050
                - ${ORDERER2_HOST}:8050
                - ${ORDERER3_HOST}:9050

            Organizations:
            - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            SampleConsortium:
                Organizations:
                - *Org1
                - *Org2
                - *Org3
