version: "2"

networks:
  acedefi:

services:
  # ca-org1:
  #   image: hyperledger/fabric-ca
  #   environment:
  #     - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
  #     - FABRIC_CA_SERVER_CA_NAME=ca.${DOMAIN_OF_ORGANIZATION}
  #     - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.${DOMAIN_OF_ORGANIZATION}-cert.pem
  #     - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/priv_sk
  #     - FABRIC_CA_SERVER_TLS_ENABLED=true
  #     - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-tls/tlsca.${DOMAIN_OF_ORGANIZATION}-cert.pem
  #     - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-tls/priv_sk
  #   ports:
  #     - "7054:7054"
  #   command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
  #   volumes:
  #     - ./crypto-config/peerOrganizations/${DOMAIN_OF_ORGANIZATION}/ca/:/etc/hyperledger/fabric-ca-server-config
  #     - ./crypto-config/peerOrganizations/${DOMAIN_OF_ORGANIZATION}/tlsca/:/etc/hyperledger/fabric-ca-server-tls
  #   container_name: ca.${DOMAIN_OF_ORGANIZATION}
  #   hostname: ca.${DOMAIN_OF_ORGANIZATION}
  #   networks:
  #     - ${NETWORK_NAME}


  couchdb0:
    container_name: ${DB_NAME_ZERO}
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 5984:5984
    networks:
      - ${NETWORK_NAME}

  couchdb1:
    container_name: ${DB_NAME_ONE}
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 6984:5984
    networks:
      - ${NETWORK_NAME}

  peer0.org1:
    container_name: peer0.${DOMAIN_OF_ORGANIZATION}
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - FABRIC_LOGGING_SPEC=DEBUG
      - ORDERER_GENERAL_LOGLEVEL=DEBUG
      - CORE_PEER_LOCALMSPID=${ORG_MSP}

      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_${NETWORK_NAME}

      - CORE_PEER_ID=peer0.${DOMAIN_OF_ORGANIZATION}
      - CORE_PEER_ADDRESS=peer0.${DOMAIN_OF_ORGANIZATION}:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.${DOMAIN_OF_ORGANIZATION}:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      # Peer used to bootstrap gossip within organisation
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.${DOMAIN_OF_ORGANIZATION}:8051
      # Exposed for discovery Service
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.${DOMAIN_OF_ORGANIZATION}:7051

      # - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9440

      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=${DB_NAME_ZERO}:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
      - CORE_METRICS_PROVIDER=prometheus
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
    depends_on:
      - ${DB_NAME_ZERO}
    ports:
      - 7051:7051
    volumes:
      - ./crypto-config/peerOrganizations/${DOMAIN_OF_ORGANIZATION}/peers/peer0.${DOMAIN_OF_ORGANIZATION}/msp:/etc/hyperledger/crypto/peer/msp
      - ./crypto-config/peerOrganizations/${DOMAIN_OF_ORGANIZATION}/peers/peer0.${DOMAIN_OF_ORGANIZATION}/tls:/etc/hyperledger/crypto/peer/tls
      - /var/run/:/host/var/run/
      - ./:/etc/hyperledger/channel/
    networks:
      - ${NETWORK_NAME}

  peer1.org1:
    container_name: peer1.${DOMAIN_OF_ORGANIZATION}
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - FABRIC_LOGGING_SPEC=DEBUG
      - ORDERER_GENERAL_LOGLEVEL=debug
      - CORE_PEER_LOCALMSPID=${ORG_MSP}

      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_${NETWORK_NAME}

      - CORE_PEER_ID=peer1.${DOMAIN_OF_ORGANIZATION}
      - CORE_PEER_ADDRESS=peer1.${DOMAIN_OF_ORGANIZATION}:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.${DOMAIN_OF_ORGANIZATION}:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      # Exposed for discovery Service
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.${DOMAIN_OF_ORGANIZATION}:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.${DOMAIN_OF_ORGANIZATION}:7051

      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=${DB_NAME_ONE}:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
      - CORE_METRICS_PROVIDER=prometheus
      # - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9440
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
    ports:
      - 8051:8051
    volumes:
      - ./crypto-config/peerOrganizations/${DOMAIN_OF_ORGANIZATION}/peers/peer1.${DOMAIN_OF_ORGANIZATION}/msp:/etc/hyperledger/crypto/peer/msp
      - ./crypto-config/peerOrganizations/${DOMAIN_OF_ORGANIZATION}/peers/peer1.${DOMAIN_OF_ORGANIZATION}/tls:/etc/hyperledger/crypto/peer/tls
      - /var/run/:/host/var/run/
      - ./:/etc/hyperledger/channel/
    networks:
      - ${NETWORK_NAME}

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.${DOMAIN_OF_ORGANIZATION}:7051
      - CORE_PEER_LOCALMSPID=${ORG_MSP}
      # - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/channel/crypto-config/Org1MSP

      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/channel/crypto-config/peerOrganizations/${DOMAIN_OF_ORGANIZATION}/peers/peer0.${DOMAIN_OF_ORGANIZATION}/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/channel/crypto-config/peerOrganizations/${DOMAIN_OF_ORGANIZATION}/peers/peer0.${DOMAIN_OF_ORGANIZATION}/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/channel/crypto-config/peerOrganizations/${DOMAIN_OF_ORGANIZATION}/peers/peer0.${DOMAIN_OF_ORGANIZATION}/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/channel/crypto-config/peerOrganizations/${DOMAIN_OF_ORGANIZATION}/users/Admin@${DOMAIN_OF_ORGANIZATION}/msp

      - CORE_CHAINCODE_KEEPALIVE=10 
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    networks:
      - ${NETWORK_NAME}
    volumes:
      - /var/run/:/host/var/run/
      # - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ./crypto-config/peerOrganizations/${DOMAIN_OF_ORGANIZATION}/:/etc/hyperledger/channel/crypto-config/peerOrganizations/${DOMAIN_OF_ORGANIZATION}/
      - ./../vm2/crypto-config/peerOrganizations/${DOMAIN_OF_ORGANIZATION_TWO}/:/etc/hyperledger/channel/crypto-config/peerOrganizations/${DOMAIN_OF_ORGANIZATION_TWO}/
      - ./../vm3/crypto-config/peerOrganizations/${DOMAIN_OF_ORGANIZATION_THREE}/:/etc/hyperledger/channel/crypto-config/peerOrganizations/${DOMAIN_OF_ORGANIZATION_THREE}/
      - ./../vm4/crypto-config/ordererOrganizations/${DOMAIN_OF_ORDERER}/:/etc/hyperledger/channel/crypto-config/ordererOrganizations/${DOMAIN_OF_ORDERER}/
