version: '2'

networks:
  acedefi:

services:
  ca:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.${DOMAIN_OF_ORGANIZATION}
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./fabric-ca/${ORGANIZATION_NAME_LOWERCASE}:/etc/hyperledger/fabric-ca-server
    container_name: ca.${DOMAIN_OF_ORGANIZATION}
    hostname: ca.${DOMAIN_OF_ORGANIZATION}
    networks:
      - acedefi